name: Formatting

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  csharpier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Restore .NET tools
        run: dotnet tool restore
      - name: Check formatting with CSharpier
        run: dotnet tool run csharpier -- check .
